---
title: "data558a_week04_participation"
author: "WEconnect Health"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: bookdown::html_document2
---

```{r setup}
library(tidyverse)
library(kableExtra)
```

```{r first_chunk, echo = TRUE}
x <- 2 + 2
```

```{r starwars-plot, fig.cap = "A ggplot of Starwars character heights"}
g <- ggplot(starwars[which(starwars$species=="Human" & is.na(starwars$height)==FALSE),], aes(x = reorder(factor(name), -height), y = height))
g + geom_bar(stat = "identity") +
  theme_bw() +
  labs(title = "Heights of Star Wars Characters",
       x = "Character",
       y = "Height") +
  theme(axis.text.x = element_text(angle = 40, hjust = 1))
```

Some text referring to \@ref(fig:starwars-plot)

```{r starwars-tbl}
head(starwars[which(starwars$species=="Human"),],20) %>%
  select(name, height) %>%
  arrange(desc(height)) %>%
  knitr::kable(caption = "A knitr kable table of starwars data")
```
  
We can see, in table \@ref(tab:starwars-tbl) that people have heights.
